name: Deploy SoText Web

on:
  push:
    branches:
      - sotext.app
    paths:
      - 'web/**'
  workflow_dispatch: # Allows manual trigger

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Checkout
        uses: actions/checkout@v4

      - name: 🛠️ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: web/package-lock.json

      - name: 📦 Build Web App
        run: |
          cd web
          npm install
          npm run build

      - name: 🚀 Deploy to Host
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: server8.webhostmost.com
          username: qthdunpa
          password: ${{ secrets.SFTP_PASSWORD }}
          port: 2323
          protocol: sftp
          local-dir: ./web/dist/
          server-dir: ./public_html/ # Verify if this is the correct path for sotext.app
          dangerous-clean-slate: false
